# This docker-compose.yml file is used to start the weaviate and ollama services for testing.
# It is not used in the production environment.
services:
  pgvector:
    image: registry.cn-hangzhou.aliyuncs.com/lacogito/pgvector:pg17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vectordb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/init-db.sql:/docker-entrypoint-initdb.d/10-create-soothe.sql:ro

volumes:
  postgres_data:
